version: '3'

services:
  db:
    container_name: catalog1
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db

    ports:
      - "5433:5432"


  pgdb:
    container_name: catalog
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"


  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - django

  celery-beat:
    build: .
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - django
    restart: on-failure
    
  

volumes:
  pgdbdata: null